force-app/main/default/objects/Real_Estate_Property__c/Real_Estate_Property__c.object-meta.xml
<CustomObject>
    <label>Real Estate Property</label>
    <nameField>
        <label>Real Estate Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Real Estate Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Real_Estate_Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Real_Estate_Property__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rent and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Real_Estate_Property__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Independent House</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Row House</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RealEstatePropertyController.cls
public with sharing class RealEstatePropertyController {

    public class Filters{
        @AuraEnabled
        public String searchKey{get;set;}
        @AuraEnabled
        public Decimal maxPrice{get;set;}
        @AuraEnabled
        public String[] types{get;set;}
        @AuraEnabled
        public String saleType{get;set;}
    }

    /**
    * @description : Create a dynamic query with different values that front send to apex.
    * @param filters Class(Filter) : Wrapper class to send especific values for a dynamic query
    * @return List<Real_Estate_Property__c> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<Real_Estate_Property__c> getRealEstateProperties(Filters filters){
        try {
            String key,saleType, whereClause = '';
            Decimal maxPrice;
            String[] types,criteria = new List<String>{};
            System.debug('shego el lecherooo');
            System.debug(filters);
            if(filters != null){
                System.debug('Hay filters');
                maxPrice = filters.maxPrice;
                types = filters.types;
                saleType = filters.saleType;
                if(String.isNotEmpty(filters.searchKey)){
                    System.debug('Hay searchkey');
                    key = '%' + String.escapeSingleQuotes(filters.searchKey) + '%';
                    criteria.add('Name LIKE :key');
                    System.debug(criteria);
                }
                if(maxPrice >= 0){
                    System.debug('Hay maxprice');
                    criteria.add('Price__c <= :maxPrice');
                    System.debug(criteria);
                }
                if(filters.types != null && filters.types.size() > 0){
                    System.debug('Hay types');
                    criteria.add('Type__c IN :types');
                    System.debug(criteria);
                }
                if(String.isNotEmpty(saleType)){
                    System.debug('Hay saleType');
                    criteria.add('Sale_Type__c = :saleType');
                    System.debug(criteria);
                }
                if(criteria.size() > 0){
                    System.debug('Hay criterias');
                    whereClause = 'WHERE ' + String.join(criteria, ' AND ');
                    System.debug(whereClause);
                }
            }
            System.debug('a punto de escribir el query');
            String query = 'SELECT Id, Name, Price__c, Sale_Type__c, Type__c, Picture_URL__c FROM Real_Estate_Property__c ' + whereClause + ' WITH SECURITY_ENFORCED ' + 'ORDER BY Name';
            System.debug(query);
            return Database.query(query);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description : Get similar Real Estate Property records based on the type.
    * @param propertyId Id : Record Id of the property record in order to not fetch the same record again
    * @param type String : parameter to check for similar records
    * @return Real_Estate_Property__c[]
    **/
    @AuraEnabled(cacheable=true)
    public static Real_Estate_Property__c[] getSimilarRealEstateProperties(Id propertyId, String type){
        return [SELECT Id, Name, Price__c, Sale_Type__c, Picture_URL__c FROM Real_Estate_Property__c WHERE Type__c = :type AND Id != :propertyId LIMIT 6];
    }
}